### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by yijunyu** [trusted-programming/curs#1]
# Tasks

## Extract Learning Samples

- [x] Extract functions from Crates-IO index and split them into safe and unsafe classes
- [x] Extract blocks from Crates-IO index and split them into safe and unsafe classes
- [x] Annotate extracted code with inlay hints

## Train a model
- [x] Use CodeBERT to train a classification model on safe/unsafe functions
- [x] Use CodeBERT to train a classification model on safe/unsafe blocks
- [x] Convert the PyTorch model into an Rust_BERT model on Huggingface for functions
- [ ] Convert the PyTorch model into an Rust_BERT model on Huggingface for blocks

## Inference with the model
- [x] Develop a VSCode Plugin to Classify a function at cursor
- [x] Compare the performance between Rust_BERT and CodeBERT for inferencing time
- [ ] Develop a VSCode Plugin to Classify a block at cursor
